### ISSUE TITLE
After update to js-controller 3.3.1 several wrong types in log

### ISSUE THREAD

**Issue by Grothesk242** [DrozmotiX/ioBroker.tado#214]
iobroker 3.3.1
node v16.0.0
npm 6.14.13
tado 0.2.6

```
2021-04-30 00:49:02.728  - info: tado.0 (2802) starting. Version 0.2.6 in /opt/iobroker/node_modules/iobroker.tado, node: v16.0.0, js-controller: 3.3.1
2021-04-30 00:49:03.284  - info: tado.0 (2802) Connected to Tado cloud, initialyzing ...
2021-04-30 00:49:05.257  - warn: tado.0 (2802) State value to set for "tado.0.109324.Rooms.1.devices.VA0879953152.info.serialNo" has wrong type "string" but has to be "number"
2021-04-30 00:49:05.259  - warn: tado.0 (2802) State value to set for "tado.0.109324.Rooms.1.devices.VA0879953152.info.currentFwVersion" has wrong type "string" but has to be "number"
2021-04-30 00:49:05.628  - warn: tado.0 (2802) State value to set for "tado.0.109324.Rooms.1.nextScheduleChange" has wrong type "string" but has to be "array"
2021-04-30 00:49:05.633  - warn: tado.0 (2802) State value to set for "tado.0.109324.Rooms.1.nextTimeBlock" has wrong type "string" but has to be "array"
2021-04-30 00:49:06.154  - warn: tado.0 (2802) State value to set for "tado.0.109324.Rooms.3.devices.VA3330606336.info.serialNo" has wrong type "string" but has to be "number"
2021-04-30 00:49:06.156  - warn: tado.0 (2802) State value to set for "tado.0.109324.Rooms.3.devices.VA3330606336.info.currentFwVersion" has wrong type "string" but has to be "number"
2021-04-30 00:49:06.496  - warn: tado.0 (2802) State value to set for "tado.0.109324.Rooms.3.nextScheduleChange" has wrong type "string" but has to be "array"
2021-04-30 00:49:06.498  - warn: tado.0 (2802) State value to set for "tado.0.109324.Rooms.3.nextTimeBlock" has wrong type "string" but has to be "array"
2021-04-30 00:49:07.036  - warn: tado.0 (2802) State value to set for "tado.0.109324.Rooms.2.devices.VA1030948096.info.serialNo" has wrong type "string" but has to be "number"
2021-04-30 00:49:07.038  - warn: tado.0 (2802) State value to set for "tado.0.109324.Rooms.2.devices.VA1030948096.info.currentFwVersion" has wrong type "string" but has to be "number"
2021-04-30 00:49:07.385  - warn: tado.0 (2802) State value to set for "tado.0.109324.Rooms.2.nextScheduleChange" has wrong type "string" but has to be "array"
2021-04-30 00:49:07.392  - warn: tado.0 (2802) State value to set for "tado.0.109324.Rooms.2.nextTimeBlock" has wrong type "string" but has to be "array"
2021-04-30 00:49:08.211  - warn: tado.0 (2802) State value to set for "tado.0.109324.Rooms.4.devices.VA2760180992.info.serialNo" has wrong type "string" but has to be "number"
2021-04-30 00:49:08.212  - warn: tado.0 (2802) State value to set for "tado.0.109324.Rooms.4.devices.VA2760180992.info.currentFwVersion" has wrong type "string" but has to be "number"
2021-04-30 00:49:08.578  - warn: tado.0 (2802) State value to set for "tado.0.109324.Rooms.4.nextScheduleChange" has wrong type "string" but has to be "array"
2021-04-30 00:49:08.579  - warn: tado.0 (2802) State value to set for "tado.0.109324.Rooms.4.nextTimeBlock" has wrong type "string" but has to be "array"
```

**Comment by HGlab01** [comment]
Thanks, we will adjust the state definitions.
I guess a lot of adapters are impacted and I assume this will be heavily discussed here https://github.com/ioBroker/ioBroker.js-controller/issues/1299

**Comment by itProfi** [comment]
Same problem
![Скриншот 30-04-2021 085557](https://user-images.githubusercontent.com/6728198/116655048-0ab73e80-a993-11eb-8b96-1465a5707ae8.jpg)

**Comment by HGlab01** [comment]
> Same problem
> ![Скриншот 30-04-2021 085557](https://user-images.githubusercontent.com/6728198/116655048-0ab73e80-a993-11eb-8b96-1465a5707ae8.jpg)

But this was caused by sonoff adapter, isn't it?  ;-)

**Comment by HGlab01** [comment]
You can test the fix by installing manually (with the cat) the version
DrozmotiX/ioBroker.tado#60c43188f82f9649b4140d10494ebb406a2eb8ae
![image](https://user-images.githubusercontent.com/54232526/116656549-27507800-a98d-11eb-956a-22d1c372402a.png)

**Comment by cracyfloyd** [comment]
i have installed version: DrozmotiX/ioBroker.tado#60c43188f82f9649b4140d10494ebb406a2eb8ae
but the warnings are still there. See log.

2021-04-30 10:28:33.816 - warn: tado.0 (14101) State value to set for "tado.0.222490.Rooms.10.devices.VA2708740608.info.serialNo" has wrong type "string" but has to be "number"
--
2021-04-30 10:28:33.826 - warn: tado.0 (14101) State value to set for "tado.0.222490.Rooms.10.devices.VA2708740608.info.currentFwVersion" has wrong type "string" but has to be "number"
2021-04-30 10:28:34.202 - warn: tado.0 (14101) State value to set for "tado.0.222490.Rooms.10.nextScheduleChange" has wrong type "string" but has to be "array"
2021-04-30 10:28:34.206 - warn: tado.0 (14101) State value to set for "tado.0.222490.Rooms.10.nextTimeBlock" has wrong type "string" but has to be "array"
2021-04-30 10:28:35.101 - warn: tado.0 (14101) State value to set for "tado.0.222490.Rooms.1.devices.VA4119202304.info.serialNo" has wrong type "string" but has to be "number"
2021-04-30 10:28:35.104 - warn: tado.0 (14101) State value to set for "tado.0.222490.Rooms.1.devices.VA4119202304.info.currentFwVersion" has wrong type "string" but has to be "number"
2021-04-30 10:28:35.515 - warn: tado.0 (14101) State value to set for "tado.0.222490.Rooms.1.nextScheduleChange" has wrong type "string" but has to be "array"
2021-04-30 10:28:35.518 - warn: tado.0 (14101) State value to set for "tado.0.222490.Rooms.1.nextTimeBlock" has wrong type "string" but has to be "array"
2021-04-30 10:28:35.915 - warn: tado.0 (14101) State value to set for "tado.0.222490.Rooms.13.devices.SU2308972288.info.serialNo" has wrong type "string" but has to be "number"
2021-04-30 10:28:35.916 - warn: tado.0 (14101) State value to set for "tado.0.222490.Rooms.13.devices.SU2308972288.info.currentFwVersion" has wrong type "string" but has to be "number"
2021-04-30 10:28:35.948 - warn: tado.0 (14101) State value to set for "tado.0.222490.Rooms.13.devices.VA2743405056.info.serialNo" has wrong type "string" but has to be "number"
2021-04-30 10:28:35.950 - warn: tado.0 (14101) State value to set for "tado.0.222490.Rooms.13.devices.VA2743405056.info.currentFwVersion" has wrong type "string" but has to be "number"
2021-04-30 10:28:36.045 - warn: tado.0 (14101) State value to set for "tado.0.222490.Rooms.13.devices.VA2350191104.info.serialNo" has wrong type "string" but has to be "number"
2021-04-30 10:28:36.047 - warn: tado.0 (14101) State value to set for "tado.0.222490.Rooms.13.devices.VA2350191104.info.currentFwVersion" has wrong type "string" but has to be "number"
2021-04-30 10:28:36.425 - warn: tado.0 (14101) State value to set for "tado.0.222490.Rooms.13.nextScheduleChange" has wrong type "string" but has to be "array"
2021-04-30 10:28:36.426 - warn: tado.0 (14101) State value to set for "tado.0.222490.Rooms.13.nextTimeBlock" has wrong type "string" but has to be "array"
2021-04-30 10:28:36.829 - warn: tado.0 (14101) State value to set for "tado.0.222490.Rooms.2.devices.VA3232172800.info.serialNo" has wrong type "string" but has to be "number"
2021-04-30 10:28:36.834 - warn: tado.0 (14101) State value to set for "tado.0.222490.Rooms.2.devices.VA3232172800.info.currentFwVersion" has wrong type "string" but has to be "number"
2021-04-30 10:28:37.196 - warn: tado.0 (14101) State value to set for "tado.0.222490.Rooms.2.nextScheduleChange" has wrong type "string" but has to be "array"
2021-04-30 10:28:37.197 - warn: tado.0 (14101) State value to set for "tado.0.222490.Rooms.2.nextTimeBlock" has wrong type "string" but has to be "array"
2021-04-30 10:28:37.637 - warn: tado.0 (14101) State value to set for "tado.0.222490.Rooms.8.devices.VA0586878720.info.serialNo" has wrong type "string" but has to be "number"
2021-04-30 10:28:37.641 - warn: tado.0 (14101) State value to set for "tado.0.222490.Rooms.8.devices.VA0586878720.info.currentFwVersion" has wrong type "string" but has to be "number"
2021-04-30 10:28:38.005 - warn: tado.0 (14101) State value to set for "tado.0.222490.Rooms.8.nextScheduleChange" has wrong type "string" but has to be "array"
2021-04-30 10:28:38.007 - warn: tado.0 (14101) State value to set for "tado.0.222490.Rooms.8.nextTimeBlock" has wrong type "string" but has to be "array"
2021-04-30 10:28:38.426 - warn: tado.0 (14101) State value to set for "tado.0.222490.Rooms.7.devices.VA3405841664.info.serialNo" has wrong type "string" but has to be "number"
2021-04-30 10:28:38.429 - warn: tado.0 (14101) State value to set for "tado.0.222490.Rooms.7.devices.VA3405841664.info.currentFwVersion" has wrong type "string" but has to be "number"
2021-04-30 10:28:38.807 - warn: tado.0 (14101) State value to set for "tado.0.222490.Rooms.7.nextScheduleChange" has wrong type "string" but has to be "array"
2021-04-30 10:28:38.813 - warn: tado.0 (14101) State value to set for "tado.0.222490.Rooms.7.nextTimeBlock" has wrong type "string" but has to be "array"
2021-04-30 10:28:39.336 - warn: tado.0 (14101) State value to set for "tado.0.222490.Rooms.9.devices.VA1668618752.info.serialNo" has wrong type "string" but has to be "number"
2021-04-30 10:28:39.339 - warn: tado.0 (14101) State value to set for "tado.0.222490.Rooms.9.devices.VA1668618752.info.currentFwVersion" has wrong type "string" but has to be "number"
2021-04-30 10:28:39.728 - warn: tado.0 (14101) State value to set for "tado.0.222490.Rooms.9.nextScheduleChange" has wrong type "string" but has to be "array"
2021-04-30 10:28:39.729 - warn: tado.0 (14101) State value to set for "tado.0.222490.Rooms.9.nextTimeBlock" has wrong type "string" but has to be "array"
2021-04-30 10:28:40.706 - warn: tado.0 (14101) State value to set for "tado.0.222490.Rooms.16.devices.VA1577458944.info.serialNo" has wrong type "string" but has to be "number"
2021-04-30 10:28:40.708 - warn: tado.0 (14101) State value to set for "tado.0.222490.Rooms.16.devices.VA1577458944.info.currentFwVersion" has wrong type "string" but has to be "number"
2021-04-30 10:28:41.098 - warn: tado.0 (14101) State value to set for "tado.0.222490.Rooms.16.nextScheduleChange" has wrong type "string" but has to be "array"
2021-04-30 10:28:41.100 - warn: tado.0 (14101) State value to set for "tado.0.222490.Rooms.16.nextTimeBlock" has wrong type "string" but has to be "array"
2021-04-30 10:28:41.475 - warn: tado.0 (14101) State value to set for "tado.0.222490.Rooms.3.devices.RU3795520512.info.serialNo" has wrong type "string" but has to be "number"
2021-04-30 10:28:41.476 - warn: tado.0 (14101) State value to set for "tado.0.222490.Rooms.3.devices.RU3795520512.info.currentFwVersion" has wrong type "string" but has to be "number"
2021-04-30 10:28:41.870 - warn: tado.0 (14101) State value to set for "tado.0.222490.Rooms.3.nextScheduleChange" has wrong type "string" but has to be "array"
2021-04-30 10:28:41.872 - warn: tado.0 (14101) State value to set for "tado.0.222490.Rooms.3.nextTimeBlock" has wrong type "string" but has to be "array"
2021-04-30 10:28:42.265 - warn: tado.0 (14101) State value to set for "tado.0.222490.Rooms.17.devices.VA2332564736.info.serialNo" has wrong type "string" but has to be "number"
2021-04-30 10:28:42.266 - warn: tado.0 (14101) State value to set for "tado.0.222490.Rooms.17.devices.VA2332564736.info.currentFwVersion" has wrong type "string" but has to be "number"
2021-04-30 10:28:42.670 - warn: tado.0 (14101) State value to set for "tado.0.222490.Rooms.17.nextScheduleChange" has wrong type "string" but has to be "array"
2021-04-30 10:28:42.672 - warn: tado.0 (14101) State value to set for "tado.0.222490.Rooms.17.nextTimeBlock" has wrong type "string" but has to be "array"
2021-04-30 10:28:43.023 - warn: tado.0 (14101) State value to set for "tado.0.222490.Rooms.0.devices.BU1901200896.info.serialNo" has wrong type "string" but has to be "number"
2021-04-30 10:28:43.029 - warn: tado.0 (14101) State value to set for "tado.0.222490.Rooms.0.devices.BU1901200896.info.currentFwVersion" has wrong type "string" but has to be "number"
2021-04-30 10:28:43.031 - warn: tado.0 (14101) State value to set for "tado.0.222490.Rooms.0.devices.BU1901200896.info.isDriverConfigured" has wrong type "undefined" but has to be "boolean"
2021-04-30 10:28:43.060 - warn: tado.0 (14101) State value to set for "tado.0.222490.Rooms.0.devices.RU3795520512.info.serialNo" has wrong type "string" but has to be "number"
2021-04-30 10:28:43.064 - warn: tado.0 (14101) State value to set for "tado.0.222490.Rooms.0.devices.RU3795520512.info.currentFwVersion" has wrong type "string" but has to be "number"
2021-04-30 10:28:43.466 - warn: tado.0 (14101) State value to set for "tado.0.222490.Rooms.0.nextScheduleChange" has wrong type "string" but has to be "array"
2021-04-30 10:28:43.467 - warn: tado.0 (14101) State value to set for "tado.0.222490.Rooms.0.nextTimeBlock" has wrong type "string" but has to be "array"

**Comment by HGlab01** [comment]
Ah! I forgot to mention, that you have to delete the corresponding states manually or to delete the adapter instance and create it again.
This is an general issue of the current adapter implementation, which will be improved in a planed update.

I just missed one state --> clearZoneOverlay --> update:
DrozmotiX/ioBroker.tado#6686761f755919ac3618021c580b7b8ece4c073c

**Comment by cracyfloyd** [comment]
Now i have delete the adapter instance.
but some messages come again in the log.


tado.0 | 2021-04-30 11:15:45.914 | warn | State value to set for "tado.0.222490.Rooms.0.devices.BU1901200896.info.isDriverConfigured" has wrong type "undefined" but has to be "boolean"
-- | -- | -- | --
tado.0 | 2021-04-30 11:15:45.322 | warn | State value to set for "tado.0.222490.Rooms.0.devices.BU1901200896.info.isDriverConfigured" has wrong type "undefined" but has to be "boolean"
tado.0 | 2021-04-30 11:15:45.226 | warn | State value to set for "tado.0.222490.Rooms.17.overlay.clearZoneOverlay" has wrong type "string" but has to be "boolean"
tado.0 | 2021-04-30 11:15:44.657 | warn | State value to set for "tado.0.222490.Rooms.17.overlay.clearZoneOverlay" has wrong type "string" but has to be "boolean"
tado.0 | 2021-04-30 11:15:44.457 | warn | State value to set for "tado.0.222490.Rooms.3.overlay.clearZoneOverlay" has wrong type "string" but has to be "boolean"
tado.0 | 2021-04-30 11:15:43.528 | warn | State value to set for "tado.0.222490.Rooms.3.overlay.clearZoneOverlay" has wrong type "string" but has to be "boolean"
tado.0 | 2021-04-30 11:15:43.207 | warn | State value to set for "tado.0.222490.Rooms.16.overlay.clearZoneOverlay" has wrong type "string" but has to be "boolean"
tado.0 | 2021-04-30 11:15:42.474 | warn | State value to set for "tado.0.222490.Rooms.16.overlay.clearZoneOverlay" has wrong type "string" but has to be "boolean"
tado.0 | 2021-04-30 11:15:41.763 | warn | State value to set for "tado.0.222490.Rooms.9.overlay.clearZoneOverlay" has wrong type "string" but has to be "boolean"
tado.0 | 2021-04-30 11:15:40.885 | warn | State value to set for "tado.0.222490.Rooms.9.overlay.clearZoneOverlay" has wrong type "string" but has to be "boolean"
tado.0 | 2021-04-30 11:15:40.717 | warn | State value to set for "tado.0.222490.Rooms.7.overlay.clearZoneOverlay" has wrong type "string" but has to be "boolean"
tado.0 | 2021-04-30 11:15:39.923 | warn | State value to set for "tado.0.222490.Rooms.7.overlay.clearZoneOverlay" has wrong type "string" but has to be "boolean"
tado.0 | 2021-04-30 11:15:39.705 | warn | State value to set for "tado.0.222490.Rooms.8.overlay.clearZoneOverlay" has wrong type "string" but has to be "boolean"
tado.0 | 2021-04-30 11:15:38.844 | warn | State value to set for "tado.0.222490.Rooms.8.overlay.clearZoneOverlay" has wrong type "string" but has to be "boolean"
tado.0 | 2021-04-30 11:15:38.629 | warn | State value to set for "tado.0.222490.Rooms.2.overlay.clearZoneOverlay" has wrong type "string" but has to be "boolean"
tado.0 | 2021-04-30 11:15:37.837 | warn | State value to set for "tado.0.222490.Rooms.2.overlay.clearZoneOverlay" has wrong type "string" but has to be "boolean"
tado.0 | 2021-04-30 11:15:37.590 | warn | State value to set for "tado.0.222490.Rooms.13.overlay.clearZoneOverlay" has wrong type "string" but has to be "boolean"
tado.0 | 2021-04-30 11:15:36.233 | warn | State value to set for "tado.0.222490.Rooms.13.overlay.clearZoneOverlay" has wrong type "string" but has to be "boolean"
tado.0 | 2021-04-30 11:15:35.760 | warn | State value to set for "tado.0.222490.Rooms.1.overlay.clearZoneOverlay" has wrong type "string" but has to be "boolean"
tado.0 | 2021-04-30 11:15:34.662 | warn | State value to set for "tado.0.222490.Rooms.10.overlay.clearZoneOverlay" has wrong type "string" but has to be "boolean"
tado.0 | 2021-04-30 11:15:34.646 | warn | State value to set for "tado.0.222490.Rooms.1.overlay.clearZoneOverlay" has wrong type "string" but has to be "boolean"
tado.0 | 2021-04-30 11:15:33.436 | warn | State value to set for "tado.0.222490.Rooms.10.overlay.clearZoneOverlay" has wrong type "string" but has to be "boolean"
tado.0 | 2021-04-30 11:15:30.741 | warn | State "tado.0.222490.Rooms.17.overlay.termination.remainingTimeInSeconds" has no existing object, this might lead to an error in future versions
tado.0 | 2021-04-30 11:15:30.740 | warn | State "tado.0.222490.Rooms.17.overlay.termination.durationInSeconds" has no existing object, this might lead to an error in future versions
tado.0 | 2021-04-30 11:15:30.739 | warn | State "tado.0.222490.Rooms.17.overlay.termination.expiry" has no existing object, this might lead to an error in future versions

**Comment by HGlab01** [comment]
clearZoneOverlay should be gone, if you take the newest one. Correct?
https://github.com/DrozmotiX/ioBroker.tado/issues/214#issuecomment-829956326

The others I have to check

**Comment by cracyfloyd** [comment]
i think no. See.


tado.0 | 2021-04-30 13:07:59.593 | warn | State value to set for "tado.0.222490.Rooms.1.overlay.clearZoneOverlay" has wrong type "string" but has to be "boolean"
-- | -- | -- | --
tado.0 | 2021-04-30 13:07:58.609 | warn | State value to set for "tado.0.222490.Rooms.10.overlay.clearZoneOverlay" has wrong type "string" but has to be "boolean"
tado.0 | 2021-04-30 13:07:25.528 | warn | State value to set for "tado.0.222490.Rooms.0.devices.BU1901200896.info.isDriverConfigured" has wrong type "undefined" but has to be "boolean"
tado.0 | 2021-04-30 13:07:16.790 | warn | State value to set for "tado.0.222490.Rooms.1.overlay.clearZoneOverlay" has wrong type "string" but has to be "boolean"
tado.0 | 2021-04-30 13:07:15.579 | warn | State value to set for "tado.0.222490.Rooms.10.overlay.clearZoneOverlay" has wrong type "string" but has to be "boolean"

**Comment by HGlab01** [comment]
ok, I guess I need a bit more time to get it done at all

**Comment by HGlab01** [comment]
Should be the last try! With this version the manual deletion is no longer necessary.
Maybe the state isDriverConfigured does not work. In my installations it is not used. If it is not working, please provide me the content of this state. Thanks!
DrozmotiX/ioBroker.tado#f757494a01011e87c2fe86fced242109fe758504

**Comment by itProfi** [comment]
js-controller 3.3.6 - same problem

**Comment by nemodil** [comment]
Same for me...

tado.0 | 2021-05-02 18:21:29.955 | info | (2092) State value to set for "tado.0.388261._info.skills" has to be one of type "string", "number", "boolean" but received type "object"

**Comment by HGlab01** [comment]
DrozmotiX/ioBroker.tado#93ea598fc2fbc18d180b6817914882592ab43316

**Comment by nemodil** [comment]
Hi,
Thanks for the update!
I've still this log entry:

tado.0 | 2021-05-03 10:48:39.612 | info | (10669) State value to set for "tado.0.388261._info.skills" has to be one of type "string", "number", "boolean" but received type "object"

**Comment by HGlab01** [comment]
I changed the interpretation of this state

DrozmotiX/ioBroker.tado#a0b269e24416ef1b23cb788d3a719f56b10371c4

**Comment by nemodil** [comment]
Yesss, Thanks! No more logs for type mismatch :-)

**Comment by rvdgaag** [comment]
Out if the blue, the Tado connector has issues again:


2021-05-03 14:58:41.040 - info: tado.0 (3008) Temperature changed for room: 1 in home: 43494 to API with: 20.5
--
2021-05-03 14:58:41.040 - info: tado.0 (3008) Send API ZoneOverlay API call Home: 43494 zone : 1 config: {"setting":{"type":"HEATING","power":"ON","temperature":{"celsius":20.5}},"termination":{"typeSkillBasedApp":"NEXT_TIME_BLOCK","durationInSeconds":null}}
2021-05-03 14:58:41.883 - error: tado.0 (3008) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2021-05-03 14:58:41.884 - error: tado.0 (3008) unhandled promise rejection: Request failed with status code 422
2021-05-03 14:58:41.887 - error: tado.0 (3008) Error: Request failed with status code 422
at createError (/opt/iobroker/node_modules/axios/lib/core/createError.js:16:15)
at settle (/opt/iobroker/node_modules/axios/lib/core/settle.js:17:12)
at IncomingMessage.handleStreamEnd (/opt/iobroker/node_modules/axios/lib/adapters/http.js:260:11)
at IncomingMessage.emit (events.js:326:22)
at IncomingMessage.EventEmitter.emit (domain.js:483:12)
at endReadableNT (_stream_readable.js:1241:12)
at processTicksAndRejections (internal/process/task_queues.js:84:21)
2021-05-03 14:58:41.888 - error: tado.0 (3008) Request failed with status code 422
2021-05-03 14:58:41.896 - info: tado.0 (3008) cleaned everything up...
2021-05-03 14:58:41.896 - info: tado.0 (3008) terminating
2021-05-03 14:58:41.896 - warn: tado.0 (3008) Terminated (UNCAUGHT_EXCEPTION): Without reason
2021-05-03 14:58:42.423 - error: host.iobrokeri7 Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2021-05-03 14:58:42.425 - error: host.iobrokeri7 Caught by controller[0]: Error: Request failed with status code 422
2021-05-03 14:58:42.425 - error: host.iobrokeri7 Caught by controller[0]: at createError (/opt/iobroker/node_modules/axios/lib/core/createError.js:16:15)
2021-05-03 14:58:42.425 - error: host.iobrokeri7 Caught by controller[0]: at settle (/opt/iobroker/node_modules/axios/lib/core/settle.js:17:12)
2021-05-03 14:58:42.425 - error: host.iobrokeri7 Caught by controller[0]: at IncomingMessage.handleStreamEnd (/opt/iobroker/node_modules/axios/lib/adapters/http.js:260:11)
2021-05-03 14:58:42.425 - error: host.iobrokeri7 Caught by controller[0]: at IncomingMessage.emit (events.js:326:22)
2021-05-03 14:58:42.425 - error: host.iobrokeri7 Caught by controller[0]: at IncomingMessage.EventEmitter.emit (domain.js:483:12)
2021-05-03 14:58:42.425 - error: host.iobrokeri7 Caught by controller[0]: at endReadableNT (_stream_readable.js:1241:12)
2021-05-03 14:58:42.425 - error: host.iobrokeri7 Caught by controller[0]: at processTicksAndRejections (internal/process/task_queues.js:84:21)
2021-05-03 14:58:42.426 - error: host.iobrokeri7 instance system.adapter.tado.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2021-05-03 14:58:42.426 - info: host.iobrokeri7 Restart adapter system.adapter.tado.0 because enabled
2021-05-03 14:59:12.444 - info: host.iobrokeri7 instance system.adapter.tado.0 started with pid 3032
2021-05-03 14:59:12.967 - info: tado.0 (3032) starting. Version 0.2.6 in /opt/iobroker/node_modules/iobroker.tado, node: v12.22.1, js-controller: 3.2.16
2021-05-03 14:59:12.977 - info: tado.0 (3032) Started with JSON-Explorer version "0.0.0-20"
2021-05-03 14:59:13.432 - info: tado.0 (3032) Connected to Tado cloud, initialyzing ...
2021-05-03 14:59:14.841 - info: tado.0 (3032) Error catched and send to Sentry, thank you collaborating! Error: State attribute definition missing for 'accessPointWiFi'
2021-05-03 14:59:14.842 - info: tado.0 (3032) Error catched and send to Sentry, thank you collaborating! Error: State attribute definition missing for 'commandTableUploadState'
2021-05-03 14:59:15.790 - info: tado.0 (3032) Initialisation finished, connected to Tado Cloud service refreshing every : 30 seconds

**Comment by pfahlenbauer** [comment]
I still got one:


tado.0 | 2021-05-04 18:28:16.433 | info | (21844) State value to set for "tado.0.566744.Rooms.1.openWindowDetected" has to be type "boolean" but received type "string"

**Comment by HGlab01** [comment]
Thanks for the info! Which value is stored in your adapter installation when the info occurs?

**Comment by HGlab01** [comment]
> I still got one:
> 
> tado.0 | 2021-05-04 18:28:16.433 | info | (21844) State value to set for "tado.0.566744.Rooms.1.openWindowDetected" has to be type "boolean" but received type "string"

Thanks for the info! Which value is stored in your adapter installation when the info occurs?

**Comment by pfahlenbauer** [comment]
I got "true" in the adapter, when the info occurs:
![image](https://user-images.githubusercontent.com/83665164/117104591-b807c900-ad7c-11eb-8d57-898243ebfb9e.png)

**Comment by HGlab01** [comment]
strange! Then, boolean should be fine! I guess Tado delivers "true" instead of true so it is a string.

You can test this one:
DrozmotiX/ioBroker.tado#b238ff65a6144be1318df33f89e0f7cfc213f4fb

**Comment by pfahlenbauer** [comment]
Works now! Thanks!

**Comment by cracyfloyd** [comment]
Now i have installed the last one. "DrozmotiX/ioBroker.tado#b238ff65a6144be1318df33f89e0f7cfc213f4fb"
and the most are fine.
but one error i have in the logfile.

<html>
<body>


tado.0 | 2021-05-05 12:49:51.776 | info | (31950) Error catched and send to Sentry, thank you collaborating! Error: State attribute definition missing for 'distance' with value '0' and type of value 'number'
-- | -- | -- | --
tado.0 | 2021-05-05 12:49:51.530 | info | (31950) Error catched and send to Sentry, thank you collaborating! Error: State attribute definition missing for 'distance' with value '0.5090345733335501' and type of value 'number'
tado.0 | 2021-05-05 12:49:51.525 | info | (31950) Error catched and send to Sentry, thank you collaborating! Error: State attribute definition missing for 'stale' with value 'false' and type of value 'boolean'
tado.0 | 2021-05-05 12:49:50.263 | info | (31950) Connected to Tado cloud, initialyzing ...


</body>
</html>

**Comment by HGlab01** [comment]
updated version:
DrozmotiX/ioBroker.tado#64ec10c044e7b46f49f089b773aaf37745d9c40f

This solves all mentioned topics except "Issue in Get all rooms Error: getaddrinfo ENOTFOUND my.tado.com" because this is/was a network issue or a server issue on tado side.

**Comment by Grothesk242** [comment]
Great to hear. When can we expect the upstream? I usually don't install adapters from git directly.
