### ISSUE TITLE
Seltsamer Fehler im Tado Adapter

### ISSUE THREAD

**Issue by Hohenbostler** [DrozmotiX/ioBroker.tado#365]
Hallo anbei mal die log Datei mit einem Fehler vom Tado Adapter. Leider kann ich nichts genaueres dazu sagen wann genau er auftritt. 

`2021-10-04 21:37:28.367  - [32minfo[39m: tado.0 (30088) Temperature changed for room '6' in home '363512' to '20'
2021-10-04 21:37:28.381  - [32minfo[39m: tado.0 (30088) Call API 'ZoneOverlay' for home '363512' and zone '6' with body {"setting":{"type":"HEATING","power":"ON","temperature":{"celsius":20}},"termination":{"typeSkillBasedApp":"MANUAL","durationInSeconds":null}}
2021-10-04 21:47:21.439  - [32minfo[39m: tado.0 (30088) Temperature changed for room '6' in home '363512' to '5'
2021-10-04 21:47:21.440  - [32minfo[39m: tado.0 (30088) Call API 'ZoneOverlay' for home '363512' and zone '6' with body {"setting":{"type":"HEATING","power":"ON","temperature":{"celsius":5}},"termination":{"typeSkillBasedApp":"MANUAL","durationInSeconds":null}}
2021-10-04 21:47:32.405  - [32minfo[39m: tado.0 (30088) Temperature changed for room '6' in home '363512' to '20'
2021-10-04 21:47:32.407  - [32minfo[39m: tado.0 (30088) Call API 'ZoneOverlay' for home '363512' and zone '6' with body {"setting":{"type":"HEATING","power":"ON","temperature":{"celsius":20}},"termination":{"typeSkillBasedApp":"MANUAL","durationInSeconds":null}}
2021-10-04 21:47:34.176  - [33mwarn[39m: heatingcontrol.0 (8924) target temperature is object null
2021-10-04 21:47:34.248  - [32minfo[39m: tado.0 (30088) Temperature changed for room '3' in home '363512' to '5'
2021-10-04 21:47:34.250  - [32minfo[39m: tado.0 (30088) Call API 'ZoneOverlay' for home '363512' and zone '3' with body {"setting":{"type":"HEATING","power":"ON","temperature":{"celsius":5}},"termination":{"typeSkillBasedApp":"NEXT_TIME_BLOCK","durationInSeconds":null}}
2021-10-04 21:47:34.699  - [33mwarn[39m: heatingcontrol.0 (8924) target temperature is object null
2021-10-04 21:47:34.773  - [32minfo[39m: tado.0 (30088) Temperature changed for room '4' in home '363512' to '5'
2021-10-04 21:47:34.775  - [32minfo[39m: tado.0 (30088) Call API 'ZoneOverlay' for home '363512' and zone '4' with body {"setting":{"type":"HEATING","power":"ON","temperature":{"celsius":5}},"termination":{"typeSkillBasedApp":"NEXT_TIME_BLOCK","durationInSeconds":null}}
2021-10-04 21:47:35.160  - [31merror[39m: tado.0 (30088) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2021-10-04 21:47:35.160  - [31merror[39m: tado.0 (30088) unhandled promise rejection: Request failed with status code 422
2021-10-04 21:47:35.166  - [31merror[39m: tado.0 (30088) Error: Request failed with status code 422
    at createError (/opt/iobroker/node_modules/iobroker.tado/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/opt/iobroker/node_modules/iobroker.tado/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/opt/iobroker/node_modules/iobroker.tado/node_modules/axios/lib/adapters/http.js:269:11)
    at IncomingMessage.emit (events.js:326:22)
    at IncomingMessage.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
2021-10-04 21:47:35.167  - [31merror[39m: tado.0 (30088) Request failed with status code 422
2021-10-04 21:47:35.177  - [32minfo[39m: tado.0 (30088) cleaned everything up...
2021-10-04 21:47:35.177  - [32minfo[39m: tado.0 (30088) terminating
2021-10-04 21:47:35.178  - [33mwarn[39m: tado.0 (30088) Terminated (UNCAUGHT_EXCEPTION): Without reason
2021-10-04 21:47:35.624  - [33mwarn[39m: heatingcontrol.1 (1382) target temperature is object null
2021-10-04 21:47:35.656  - [31merror[39m: tado.0 (30088) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2021-10-04 21:47:35.657  - [31merror[39m: tado.0 (30088) unhandled promise rejection: Request failed with status code 422
2021-10-04 21:47:35.659  - [31merror[39m: tado.0 (30088) Error: Request failed with status code 422
    at createError (/opt/iobroker/node_modules/iobroker.tado/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/opt/iobroker/node_modules/iobroker.tado/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/opt/iobroker/node_modules/iobroker.tado/node_modules/axios/lib/adapters/http.js:269:11)
    at IncomingMessage.emit (events.js:326:22)
    at IncomingMessage.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
2021-10-04 21:47:35.659  - [31merror[39m: tado.0 (30088) Request failed with status code 422
2021-10-04 21:47:35.687  - [33mwarn[39m: tado.0 (30088) redis get tado.0.363512.Rooms.5.sensorDataPoints.insideTemperature.timestamp, error - Connection is closed.
2021-10-04 21:47:35.688  - [33mwarn[39m: tado.0 (30088) redis get tado.0.363512.Rooms.5.sensorDataPoints.insideTemperature.type, error - Connection is closed.
2021-10-04 21:47:35.689  - [33mwarn[39m: tado.0 (30088) redis get tado.0.363512.Rooms.5.sensorDataPoints.insideTemperature.precision.celsius, error - Connection is closed.
2021-10-04 21:47:35.690  - [33mwarn[39m: tado.0 (30088) redis get tado.0.363512.Rooms.5.sensorDataPoints.insideTemperature.precision.fahrenheit, error - Connection is closed.
2021-10-04 21:47:35.691  - [33mwarn[39m: tado.0 (30088) redis get tado.0.363512.Rooms.5.sensorDataPoints.humidity.type, error - Connection is closed.
2021-10-04 21:47:35.692  - [33mwarn[39m: tado.0 (30088) redis get tado.0.363512.Rooms.5.sensorDataPoints.humidity.percentage, error - Connection is closed.
2021-10-04 21:47:35.693  - [33mwarn[39m: tado.0 (30088) redis get tado.0.363512.Rooms.5.sensorDataPoints.humidity.timestamp, error - Connection is closed.
2021-10-04 21:47:35.695  - [33mwarn[39m: tado.0 (30088) redis get tado.0.363512.Rooms.5.overlayClearZone, error - Connection is closed.
2021-10-04 21:47:35.701  - [33mwarn[39m: tado.0 (30088) redis get tado.0.363512.Rooms.5.AwayConfig.type, error - Connection is closed.
2021-10-04 21:47:35.703  - [33mwarn[39m: tado.0 (30088) redis get tado.0.363512.Rooms.5.AwayConfig.preheatingLevel, error - Connection is closed.
2021-10-04 21:47:35.707  - [33mwarn[39m: tado.0 (30088) redis get tado.0.363512.Rooms.5.AwayConfig.minimumAwayTemperature.celsius, error - Connection is closed.
2021-10-04 21:47:35.708  - [33mwarn[39m: tado.0 (30088) redis get tado.0.363512.Rooms.5.AwayConfig.minimumAwayTemperature.fahrenheit, error - Connection is closed.
2021-10-04 21:47:35.709  - [33mwarn[39m: tado.0 (30088) redis get tado.0.363512.Rooms.7.id, error - Connection is closed.
2021-10-04 21:47:35.713  - [33mwarn[39m: tado.0 (30088) redis get tado.0.363512.Rooms.7.name, error - Connection is closed.
2021-10-04 21:47:35.717  - [33mwarn[39m: tado.0 (30088) redis get tado.0.363512.Rooms.7.type, error - Connection is closed.
2021-10-04 21:47:35.719  - [33mwarn[39m: tado.0 (30088) redis get tado.0.363512.Rooms.7.dateCreated, error - Connection is closed.
2021-10-04 21:47:35.722  - [33mwarn[39m: tado.0 (30088) redis get tado.0.363512.Rooms.7.deviceTypes, error - Connection is closed.
2021-10-04 21:47:35.724  - [33mwarn[39m: tado.0 (30088) redis get tado.0.363512.Rooms.7.devices.VA4216917504.deviceType, error - Connection is closed.
2021-10-04 21:47:35.725  - [33mwarn[39m: tado.0 (30088) redis get tado.0.363512.Rooms.7.devices.VA4216917504.serialNo, error - Connection is closed.
2021-10-04 21:47:35.859  - [31merror[39m: host.IoBroker Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2021-10-04 21:47:35.863  - [31merror[39m: host.IoBroker Caught by controller[1]: Error: Request failed with status code 422
2021-10-04 21:47:35.863  - [31merror[39m: host.IoBroker Caught by controller[1]:     at createError (/opt/iobroker/node_modules/iobroker.tado/node_modules/axios/lib/core/createError.js:16:15)
2021-10-04 21:47:35.864  - [31merror[39m: host.IoBroker Caught by controller[1]:     at settle (/opt/iobroker/node_modules/iobroker.tado/node_modules/axios/lib/core/settle.js:17:12)
2021-10-04 21:47:35.864  - [31merror[39m: host.IoBroker Caught by controller[1]:     at IncomingMessage.handleStreamEnd (/opt/iobroker/node_modules/iobroker.tado/node_modules/axios/lib/adapters/http.js:269:11)
2021-10-04 21:47:35.864  - [31merror[39m: host.IoBroker Caught by controller[1]:     at IncomingMessage.emit (events.js:326:22)
2021-10-04 21:47:35.864  - [31merror[39m: host.IoBroker Caught by controller[1]:     at IncomingMessage.EventEmitter.emit (domain.js:483:12)
2021-10-04 21:47:35.864  - [31merror[39m: host.IoBroker Caught by controller[1]:     at endReadableNT (_stream_readable.js:1241:12)
2021-10-04 21:47:35.864  - [31merror[39m: host.IoBroker Caught by controller[1]:     at processTicksAndRejections (internal/process/task_queues.js:84:21)
2021-10-04 21:47:35.865  - [31merror[39m: host.IoBroker Caught by controller[2]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2021-10-04 21:47:35.865  - [31merror[39m: host.IoBroker Caught by controller[3]: Error: Request failed with status code 422
2021-10-04 21:47:35.865  - [31merror[39m: host.IoBroker Caught by controller[3]:     at createError (/opt/iobroker/node_modules/iobroker.tado/node_modules/axios/lib/core/createError.js:16:15)
2021-10-04 21:47:35.865  - [31merror[39m: host.IoBroker Caught by controller[3]:     at settle (/opt/iobroker/node_modules/iobroker.tado/node_modules/axios/lib/core/settle.js:17:12)
2021-10-04 21:47:35.865  - [31merror[39m: host.IoBroker Caught by controller[3]:     at IncomingMessage.handleStreamEnd (/opt/iobroker/node_modules/iobroker.tado/node_modules/axios/lib/adapters/http.js:269:11)
2021-10-04 21:47:35.865  - [31merror[39m: host.IoBroker Caught by controller[3]:     at IncomingMessage.emit (events.js:326:22)
2021-10-04 21:47:35.866  - [31merror[39m: host.IoBroker Caught by controller[3]:     at IncomingMessage.EventEmitter.emit (domain.js:483:12)
2021-10-04 21:47:35.866  - [31merror[39m: host.IoBroker Caught by controller[3]:     at endReadableNT (_stream_readable.js:1241:12)
2021-10-04 21:47:35.866  - [31merror[39m: host.IoBroker Caught by controller[3]:     at processTicksAndRejections (internal/process/task_queues.js:84:21)
2021-10-04 21:47:35.866  - [31merror[39m: host.IoBroker instance system.adapter.tado.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2021-10-04 21:47:35.867  - [32minfo[39m: host.IoBroker Restart adapter system.adapter.tado.0 because enabled
2021-10-04 21:48:05.905  - [32minfo[39m: host.IoBroker instance system.adapter.tado.0 started with pid 28752
2021-10-04 21:48:07.972  - [32minfo[39m: tado.0 (28752) starting. Version 0.3.7 in /opt/iobroker/node_modules/iobroker.tado, node: v12.22.6, js-controller: 3.3.18
2021-10-04 21:48:08.006  - [32minfo[39m: tado.0 (28752) Started with JSON-Explorer version 0.1.2
2021-10-04 21:48:08.550  - [32minfo[39m: tado.0 (28752) Connected to Tado cloud, initialyzing... 
2021-10-04 21:48:13.513  - [32minfo[39m: tado.0 (28752) Initialisation finished, connected to Tado cloud service refreshing every 30 seconds

[iobroker.2021-10-04.log](https://github.com/DrozmotiX/ioBroker.tado/files/7285255/iobroker.2021-10-04.log)

`

**Comment by HGlab01** [comment]
Hallo,

du setzt offensichtlich durch ein Script oder einen anderen Adapter innerhalb einem sehr kurzen Zeitraum mehrere Temperaturänderungen ab. Vor allem die letzten beiden sind innerhalb 500ms. Ich vermute, dass deswegen der Tado-Server den Call verweigert. Könnte sogar schon eine Art DoS Abwehr sein
2021-10-04 21:47:21.439  - [32minfo[39m: tado.0 (30088) Temperature changed for room '6' in home '363512' to '5'
2021-10-04 21:47:32.405  - [32minfo[39m: tado.0 (30088) Temperature changed for room '6' in home '363512' to '20'
2021-10-04 21:47:34.248  - [32minfo[39m: tado.0 (30088) Temperature changed for room '3' in home '363512' to '5'
2021-10-04 21:47:34.773  - [32minfo[39m: tado.0 (30088) Temperature changed for room '4' in home '363512' to '5'

**Comment by HGlab01** [comment]
du kannst auch mal die Version
DrozmotiX/ioBroker.tado#9de795803dc6359c5c962748090409a784691e81
ausprobieren. Da werden nun die Calls hinter einander abgearbeitet

**Comment by HGlab01** [comment]
offensichtlich erledigt bzw. ein neues Ticket (https://github.com/DrozmotiX/ioBroker.tado/issues/374) mit ?selbem? Thema
